# Generated by Django 5.0.2 on 2024-08-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_first_name_remove_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='\\gradient.jfif', null=True, upload_to='profile/'),
        ),
    ]
