# Generated by Django 5.0.2 on 2024-08-12 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_user'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_p', to='account.profile'),
        ),
    ]
