# Generated by Django 5.0.2 on 2024-08-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_profile_image'),
        ('main', '0004_comments_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['post', 'profile'], name='main_commen_post_id_7b3a37_idx'),
        ),
        migrations.AddIndex(
            model_name='likes',
            index=models.Index(fields=['post', 'profile'], name='main_likes_post_id_24990c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='main_post_created_84fc03_idx'),
        ),
    ]
